package config

// DefaultConfigYAML is the boilerplate template generated by 'devctl config init'.
const DefaultConfigYAML = `# devctl configuration file
version: "1"

defaults:
  compose_cmd: "docker compose" # or "docker-compose"
  env_file: ".env"

# Shared Docker Network
network:
  name: "dev-network"
  driver: "bridge"
  attachable: true

# Shared Core Infrastructure
core:
  workdir: "~/workspace/core-infra"
  compose_files:
    - "docker-compose.yml"
  services:
    traefik:
      description: "Reverse Proxy & SSL termination"
    mailhog:
      description: "Local SMTP Testing mail server"
    database:
      description: "Shared PostgreSQL / MySQL container"
    redis:
      description: "Shared Redis cache"

# Managed Projects
projects:
  web-app:
    description: "Main Web Frontend Application"
    workdir: "~/workspace/web-app"
    compose_files:
      - "docker-compose.yml"
      - "docker-compose.override.yml"
    env_file: ".env.local"
    depends_on:
      network: true
      core:
        - "database"
        - "redis"
    # Absorb Makefile targets into devctl tasks
    tasks:
      migrate:
        description: "Run database migrations"
        command: "docker compose exec app go run ./cmd/migrate"
      seed:
        description: "Seed database with fixture data"
        command: "docker compose exec app go run ./cmd/seed"
      bash:
        description: "Open shell inside app container"
        command: "docker compose exec app sh"

  api-service:
    description: "Backend Microservice API"
    workdir: "~/workspace/api-service"
    compose_files:
      - "docker-compose.yml"
    depends_on:
      network: true
      core:
        - "database"
    tasks:
      test:
        description: "Run tests in container"
        command: "docker compose exec api go test ./..."
`
